"""create_ledger_entry_table

Revision ID: 6364fcaeceb9
Revises: 
Create Date: 2025-05-22 09:26:18.121994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6364fcaeceb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledgerentry',
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('debit_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credit_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledgerentry_id'), 'ledgerentry', ['id'], unique=False)
    op.create_index(op.f('ix_ledgerentry_offer_id'), 'ledgerentry', ['offer_id'], unique=False)
    op.create_index(op.f('ix_ledgerentry_reference_id'), 'ledgerentry', ['reference_id'], unique=False)
    op.create_index(op.f('ix_ledgerentry_transaction_timestamp'), 'ledgerentry', ['transaction_timestamp'], unique=False)
    op.create_index(op.f('ix_ledgerentry_transaction_type'), 'ledgerentry', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledgerentry_transaction_type'), table_name='ledgerentry')
    op.drop_index(op.f('ix_ledgerentry_transaction_timestamp'), table_name='ledgerentry')
    op.drop_index(op.f('ix_ledgerentry_reference_id'), table_name='ledgerentry')
    op.drop_index(op.f('ix_ledgerentry_offer_id'), table_name='ledgerentry')
    op.drop_index(op.f('ix_ledgerentry_id'), table_name='ledgerentry')
    op.drop_table('ledgerentry')
    # ### end Alembic commands ###
