apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valuation.fullname" . }}
  labels:
    {{- include "valuation.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "valuation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "valuation.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "valuation.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http # Placeholder, anpassa om tjänsten inte är HTTP eller har annan port
              containerPort: {{ .Values.service.port | default 8000 }} # Common port for Python services
              protocol: TCP
          # TODO: Define livenessProbe, readinessProbe, and resources
          # livenessProbe:
          #   httpGet:
          #     path: /healthz # Exempel
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /readyz # Exempel
          #     port: http
          # resources:
          #   limits:
          #     cpu: 100m
          #     memory: 128Mi
          #   requests:
          #     cpu: 50m
          #     memory: 64Mi 