"""create_creator_and_offer_tables

Revision ID: <dynamic_id>
Revises: 
Create Date: <dynamic_date>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Ensure sqlmodel is imported if its types are used directly in migrations (often not needed)


# revision identifiers, used by Alembic.
revision: str = '<dynamic_id>' # Will be replaced by actual ID
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator',
    sa.Column('platform_id', sa.String(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_platform_id'), 'creator', ['platform_id'], unique=True)
    op.create_index(op.f('ix_creator_username'), 'creator', ['username'], unique=False)
    op.create_table('offer',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_creator_id'), 'offer', ['creator_id'], unique=False)
    op.create_index(op.f('ix_offer_status'), 'offer', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_status'), table_name='offer')
    op.drop_index(op.f('ix_offer_creator_id'), table_name='offer')
    op.drop_table('offer')
    op.drop_index(op.f('ix_creator_username'), table_name='creator')
    op.drop_index(op.f('ix_creator_platform_id'), table_name='creator')
    op.drop_table('creator')
    # ### end Alembic commands ### 