"""add_index_offers_status

Revision ID: d198261eb7a4
Revises: 0001_create_tables_placeholder
Create Date: 2025-05-22 08:33:08.617749

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # Import SQLModel for potential type usage if needed in future revisions


# revision identifiers, used by Alembic.
revision = 'd198261eb7a4'
down_revision = '0001_create_tables_placeholder' # Make sure this matches your previous revision ID
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    # ### end Alembic commands ### 